# Generated by Django 4.2.1 on 2023-05-22 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0003_alter_product_options_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
