# Generated by Django 4.2.1 on 2023-05-22 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0004_remove_product_available_remove_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='uploads/product_images/thumbnails'),
        ),
    ]
