# Generated by Django 4.2.1 on 2023-05-22 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0005_product_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='thumbnail',
        ),
    ]
